[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
transpare-macros.path = "./crates/transpare-macros"
transpare.path = "./crates/transpare"
